// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TestProjectWebApi.Models;

#nullable disable

namespace TestProjectWebApi.Data
{
    public class CartConfiguration : IEntityTypeConfiguration<Cart>
    {
        public void Configure(EntityTypeBuilder<Cart> entity)
        {
            entity.HasKey(e => new { e.UserId, e.ProductId })
                .HasName("PK__Cart__DCC800200E0C8E84");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.Cart)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cart__ProductId__68487DD7");

            entity.HasOne(d => d.User)
                .WithMany(p => p.Cart)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Cart__UserId__6754599E");
        }
    }
}
