// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TestProjectWebApi.Models;

#nullable disable

namespace TestProjectWebApi.Data
{
    public class OrdersConfiguration : IEntityTypeConfiguration<Orders>
    {
        public void Configure(EntityTypeBuilder<Orders> entity)
        {
            entity.HasKey(e => e.OrderId)
                .HasName("PK__Orders__C3905BCFF4FA71C7");

            entity.Property(e => e.OrderAddress)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.OrderDate).HasColumnType("date");

            entity.Property(e => e.OrderTotal).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.User)
                .WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Orders__UserId__6B24EA82");
        }
    }
}
