// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TestProjectWebApi.Models;

#nullable disable

namespace TestProjectWebApi.Data
{
    public class ProductsConfiguration : IEntityTypeConfiguration<Products>
    {
        public void Configure(EntityTypeBuilder<Products> entity)
        {
            entity.HasKey(e => e.ProductId)
                .HasName("PK__Products__B40CC6CDF11C4EDB");

            entity.Property(e => e.ProductBrand)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.ProductDescription)
                .HasMaxLength(8000)
                .IsUnicode(false);

            entity.Property(e => e.ProductImg1)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.ProductImg2)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.ProductImg3)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.ProductImg4)
                .HasMaxLength(1000)
                .IsUnicode(false);

            entity.Property(e => e.ProductName)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.ProductPrice).HasColumnType("decimal(18, 0)");

            entity.Property(e => e.ProductStatus)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValueSql("('Available')");
        }
    }
}
