// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using TestProjectWebApi.Models;

#nullable disable

namespace TestProjectWebApi.Data
{
    public class UsersConfiguration : IEntityTypeConfiguration<Users>
    {
        public void Configure(EntityTypeBuilder<Users> entity)
        {
            entity.HasKey(e => e.UserId)
                .HasName("PK__Users__1788CC4CF744C57D");

            entity.HasIndex(e => e.UserEmail)
                .HasName("UQ__Users__08638DF8F13ACDDF")
                .IsUnique();

            entity.HasIndex(e => e.UserPhone)
                .HasName("UQ__Users__F2577C47946CC127")
                .IsUnique();

            entity.Property(e => e.IsActive)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValueSql("('Yes')");

            entity.Property(e => e.UserEmail)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.UserName)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.UserPassword)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.UserPhone)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.UserRole)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValueSql("('User')");
        }
    }
}
