// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace TestProjectMVC.Models
{
    public partial class Order
    {

        public int OrderId { get; set; }
        public int? UserId { get; set; }
        [DataType(DataType.Currency)]public decimal? OrderTotal { get; set; }
        public string OrderAddress { get; set; }
        [DataType(DataType.Date)]public DateTime? OrderDate { get; set; }

    }
}