// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TestProjectMVC.Models
{
    public partial class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        [DataType(DataType.Currency)]public decimal? ProductPrice { get; set; }
        public int? ProductStock { get; set; }
        public string ProductImg1 { get; set; }
        public string ProductImg2 { get; set; }
        public string ProductImg3 { get; set; }
        public string ProductImg4 { get; set; }
        public string ProductBrand { get; set; }
        public string ProductStatus { get; set; }
    }
}