// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;

#nullable disable

namespace TestProjectMVC.Models
{
    public partial class User
    {
        public int UserId { get; set; }
        [Required] public string UserName { get; set; }
        [Required][DataType(DataType.EmailAddress)] public string UserEmail { get; set; }
        [Required] [DataType(DataType.PhoneNumber)]public string UserPhone { get; set; }
        [Required] [DataType(DataType.Password)] public string UserPassword { get; set; }
        public string UserRole { get; set; }
        public string IsActive { get; set; }

        public override string ToString()
        {
            return JsonSerializer.Serialize(this);
        }
    }
}