// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TestProjectWebApi.Models
{
    public partial class Products
    {
        public Products()
        {
            Cart = new HashSet<Cart>();
            OrderDetails = new HashSet<OrderDetails>();
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public decimal? ProductPrice { get; set; }
        public int? ProductStock { get; set; }
        public string ProductImg1 { get; set; }
        public string ProductImg2 { get; set; }
        public string ProductImg3 { get; set; }
        public string ProductImg4 { get; set; }
        public string ProductBrand { get; set; }
        public string ProductStatus { get; set; }

        [JsonIgnore]public virtual ICollection<Cart> Cart { get; set; }
        [JsonIgnore] public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}